CHANNELS = [
    {
        "name": "3Blue1Brown",
        "creator": "Grant Sanderson",
        "url": "https://www.youtube.com/@3blue1brown",
        "subscribers_millions": 6.6,
        "level": "Beginner",
        "language": "English",
        "topics": ["Math", "Neural Networks", "Linear Algebra", "Calculus"],
        "best_for": "Visual, intuitive explanations of the math behind AI/ML",
        "free": True,
        "description": "Beautifully animated explanations of neural networks, backpropagation, and the deep math foundations of ML. The 'Neural Networks' series is essential viewing.",
    },
    {
        "name": "StatQuest with Josh Starmer",
        "creator": "Josh Starmer",
        "url": "https://www.youtube.com/@statquest",
        "subscribers_millions": 1.4,
        "level": "Beginner",
        "language": "English",
        "topics": ["Statistics", "Machine Learning", "Math"],
        "best_for": "Friendly, clear breakdowns of every ML algorithm you'll need",
        "free": True,
        "description": "BAM! Josh breaks down statistics and machine learning into bite-sized, memorable lessons. Perfect first stop for understanding any ML concept.",
    },
    {
        "name": "Andrej Karpathy",
        "creator": "Andrej Karpathy",
        "url": "https://www.youtube.com/@AndrejKarpathy",
        "subscribers_millions": 1.0,
        "level": "Advanced",
        "language": "English",
        "topics": ["Deep Learning", "LLMs", "Neural Networks", "Transformers"],
        "best_for": "Building neural networks and LLMs from scratch with one of the field's leaders",
        "free": True,
        "description": "Former Tesla AI director and OpenAI founding member. His 'Neural Networks: Zero to Hero' series builds GPT from scratch.",
    },
    {
        "name": "Two Minute Papers",
        "creator": "Károly Zsolnai-Fehér",
        "url": "https://www.youtube.com/@TwoMinutePapers",
        "subscribers_millions": 1.6,
        "level": "All Levels",
        "language": "English",
        "topics": ["Research Papers", "Computer Vision", "Generative AI"],
        "best_for": "Staying up to date with the latest AI research breakthroughs",
        "free": True,
        "description": "Short, enthusiastic summaries of cutting-edge AI papers. 'What a time to be alive!' Great for keeping a pulse on the field.",
    },
    {
        "name": "Sentdex",
        "creator": "Harrison Kinsley",
        "url": "https://www.youtube.com/@sentdex",
        "subscribers_millions": 1.4,
        "level": "Intermediate",
        "language": "English",
        "topics": ["Python", "Machine Learning", "Deep Learning", "Projects"],
        "best_for": "Hands-on Python ML projects you can actually build",
        "free": True,
        "description": "Practical, project-driven Python tutorials covering everything from neural networks to self-driving cars and finance.",
    },
    {
        "name": "DeepLearningAI",
        "creator": "Andrew Ng",
        "url": "https://www.youtube.com/@Deeplearningai",
        "subscribers_millions": 0.4,
        "level": "All Levels",
        "language": "English",
        "topics": ["Deep Learning", "ML Engineering", "AI Strategy", "LLMs"],
        "best_for": "Structured learning from the people who set the AI curriculum",
        "free": True,
        "description": "Andrew Ng's official channel — interviews, short courses, and 'The Batch' newsletter readings. Authoritative and well-produced.",
    },
    {
        "name": "Yannic Kilcher",
        "creator": "Yannic Kilcher",
        "url": "https://www.youtube.com/@YannicKilcher",
        "subscribers_millions": 0.3,
        "level": "Advanced",
        "language": "English",
        "topics": ["Research Papers", "LLMs", "Transformers", "Reinforcement Learning"],
        "best_for": "Deep, critical walkthroughs of important ML papers",
        "free": True,
        "description": "Detailed paper reviews that go beyond hype. He'll annotate the actual paper while explaining what matters and why.",
    },
    {
        "name": "Krish Naik",
        "creator": "Krish Naik",
        "url": "https://www.youtube.com/@krishnaik06",
        "subscribers_millions": 1.3,
        "level": "Intermediate",
        "language": "English",
        "topics": ["Data Science", "ML", "Deep Learning", "MLOps", "Interview Prep"],
        "best_for": "End-to-end data science career roadmap and interview prep",
        "free": True,
        "description": "Comprehensive data science and ML content with a focus on industry skills, interviews, and complete project pipelines.",
    },
    {
        "name": "CodeBasics",
        "creator": "Dhaval Patel",
        "url": "https://www.youtube.com/@codebasics",
        "subscribers_millions": 1.2,
        "level": "Beginner",
        "language": "English",
        "topics": ["Python", "Pandas", "ML", "Deep Learning", "SQL"],
        "best_for": "Step-by-step beginner Python and data science tutorials",
        "free": True,
        "description": "Clear, patient teaching style. Great structured playlists that take you from Python basics to ML and deep learning projects.",
    },
    {
        "name": "Lex Fridman",
        "creator": "Lex Fridman",
        "url": "https://www.youtube.com/@lexfridman",
        "subscribers_millions": 4.7,
        "level": "All Levels",
        "language": "English",
        "topics": ["AI Interviews", "Research", "Philosophy of AI"],
        "best_for": "Long-form conversations with the people building AI",
        "free": True,
        "description": "MIT researcher who interviews leading AI figures (Hinton, LeCun, Altman, Musk). Great for understanding the people and ideas shaping the field.",
    },
    {
        "name": "Computerphile",
        "creator": "Brady Haran / Univ. of Nottingham",
        "url": "https://www.youtube.com/@Computerphile",
        "subscribers_millions": 2.5,
        "level": "Beginner",
        "language": "English",
        "topics": ["CS Concepts", "AI", "ML", "Algorithms"],
        "best_for": "Approachable explanations of computing and AI concepts",
        "free": True,
        "description": "Academic experts explain computing concepts in accessible interviews. Many great videos on AI fundamentals, transformers, and image generation.",
    },
    {
        "name": "Stanford Online",
        "creator": "Stanford University",
        "url": "https://www.youtube.com/@stanfordonline",
        "subscribers_millions": 0.6,
        "level": "Advanced",
        "language": "English",
        "topics": ["CS229", "CS230", "CS224N", "CS231N", "Deep Learning"],
        "best_for": "Full university-grade ML/AI lectures, completely free",
        "free": True,
        "description": "Full Stanford lecture courses (CS229 ML, CS231N Computer Vision, CS224N NLP). The gold-standard academic ML education.",
    },
    {
        "name": "MIT OpenCourseWare",
        "creator": "MIT",
        "url": "https://www.youtube.com/@mitocw",
        "subscribers_millions": 5.4,
        "level": "Advanced",
        "language": "English",
        "topics": ["Linear Algebra", "AI", "ML", "Math"],
        "best_for": "Foundational MIT lectures on the math underlying AI",
        "free": True,
        "description": "Gilbert Strang's Linear Algebra course is legendary preparation for ML. Also full MIT AI and deep learning courses.",
    },
    {
        "name": "Serrano.Academy",
        "creator": "Luis Serrano",
        "url": "https://www.youtube.com/@SerranoAcademy",
        "subscribers_millions": 0.2,
        "level": "Beginner",
        "language": "English",
        "topics": ["Math for ML", "Algorithms", "LLMs", "Quantum ML"],
        "best_for": "Friendly intuition for tricky ML and math topics",
        "free": True,
        "description": "Former Google and Apple ML engineer, author of 'Grokking Machine Learning'. Famous for clear, gentle intuition-first explanations.",
    },
    {
        "name": "Data School",
        "creator": "Kevin Markham",
        "url": "https://www.youtube.com/@dataschool",
        "subscribers_millions": 0.3,
        "level": "Beginner",
        "language": "English",
        "topics": ["Pandas", "scikit-learn", "Python Data Science"],
        "best_for": "Mastering pandas and scikit-learn the right way",
        "free": True,
        "description": "Best-in-class tutorials for pandas and scikit-learn. Excellent if you want to be productive with the everyday Python data stack.",
    },
    {
        "name": "Machine Learning Street Talk",
        "creator": "Tim Scarfe & guests",
        "url": "https://www.youtube.com/@MachineLearningStreetTalk",
        "subscribers_millions": 0.15,
        "level": "Advanced",
        "language": "English",
        "topics": ["ML Theory", "Research", "Philosophy of AI"],
        "best_for": "Deep, technical conversations with top ML researchers",
        "free": True,
        "description": "Long-form, technical interviews with leading researchers. Less hype, more substance — for serious learners.",
    },
    {
        "name": "freeCodeCamp.org",
        "creator": "freeCodeCamp",
        "url": "https://www.youtube.com/@freecodecamp",
        "subscribers_millions": 11.0,
        "level": "All Levels",
        "language": "English",
        "topics": ["Full Courses", "Python", "ML", "Deep Learning", "Data Science"],
        "best_for": "Free multi-hour bootcamp-style ML and Python courses",
        "free": True,
        "description": "Hosts full-length (4-12 hour) free courses on ML, deep learning, TensorFlow, PyTorch, and data science taught by experts.",
    },
    {
        "name": "Aladdin Persson",
        "creator": "Aladdin Persson",
        "url": "https://www.youtube.com/@AladdinPersson",
        "subscribers_millions": 0.1,
        "level": "Intermediate",
        "language": "English",
        "topics": ["PyTorch", "TensorFlow", "Deep Learning Implementations"],
        "best_for": "Implementing deep learning architectures from scratch",
        "free": True,
        "description": "Clean code-along videos implementing classic and modern deep learning papers in PyTorch and TensorFlow.",
    },
    {
        "name": "AssemblyAI",
        "creator": "AssemblyAI",
        "url": "https://www.youtube.com/@AssemblyAI",
        "subscribers_millions": 0.1,
        "level": "Intermediate",
        "language": "English",
        "topics": ["NLP", "Speech AI", "PyTorch", "Transformers"],
        "best_for": "Practical NLP and speech recognition tutorials",
        "free": True,
        "description": "Clear, well-produced tutorials on transformers, NLP, and modern speech AI workflows.",
    },
    {
        "name": "Nicholas Renotte",
        "creator": "Nicholas Renotte",
        "url": "https://www.youtube.com/@NicholasRenotte",
        "subscribers_millions": 0.3,
        "level": "Intermediate",
        "language": "English",
        "topics": ["TensorFlow", "PyTorch", "Computer Vision", "Reinforcement Learning"],
        "best_for": "Fun, practical AI projects you can build over a weekend",
        "free": True,
        "description": "Energetic, project-first content — sign language detection, deep RL, object detection, and more. Great for staying motivated.",
    },
    {
        "name": "Daniel Bourke",
        "creator": "Daniel Bourke",
        "url": "https://www.youtube.com/@mrdbourke",
        "subscribers_millions": 0.2,
        "level": "Beginner",
        "language": "English",
        "topics": ["PyTorch", "Deep Learning", "ML Career"],
        "best_for": "Self-taught ML roadmap and PyTorch fundamentals",
        "free": True,
        "description": "Author of the 25-hour 'Learn PyTorch for Deep Learning' free course. Honest, friendly, and grounded in self-taught experience.",
    },
    {
        "name": "Hugging Face",
        "creator": "Hugging Face",
        "url": "https://www.youtube.com/@HuggingFace",
        "subscribers_millions": 0.07,
        "level": "Intermediate",
        "language": "English",
        "topics": ["Transformers", "LLMs", "NLP", "Diffusers"],
        "best_for": "Modern open-source LLM and transformer workflows",
        "free": True,
        "description": "Official channel of the leading open-source ML platform. Tutorials on Transformers, Diffusers, datasets, and the modern LLM stack.",
    },
]